MNT Add auto-tag workflow

diff --git a/action.yml b/action.yml
--- a/action.yml
+++ b/action.yml
@@ -1,5 +1,6 @@
 name: Branch commit and pull-request
 description: GitHub Action to create a branch, commit and a pull-request as the github-actions user
+
 inputs:
   branch:
     type: string
@@ -11,35 +12,43 @@ inputs:
     type: string
     required: false
     default: ''
+
 runs:
   using: composite
   steps:
+
     - name: Validate branch
       shell: bash
       env:
         BRANCH: ${{ inputs.branch }}
       run: |
-        if [[ "$BRANCH" =~ [^a-zA-Z0-9\./_\-] ]] || [ -z "$BRANCH" ]; then
+        git check-ref-format "heads/$BRANCH" > /dev/null
+        if [[ $? != "0" ]]; then
           echo "Invalid branch name"
           exit 1
         fi
-        if ! [[ -z $(git ls-remote --heads origin $BRANCH) ]]; then
+        if [[ $(git ls-remote --heads origin $BRANCH) != "" ]]; then
           echo "Branch $BRANCH already exists"
           exit 1
         fi
       
     - name: Branch commit and pull-request
       shell: bash
-      # Add string inputs to memory instead of using string substitution in shell script
-      # https://docs.github.com/en/actions/security-guides/security-hardening-for-github-actions#using-an-intermediate-environment-variable
       env:
         BRANCH: ${{ inputs.branch }}
         TITLE: ${{ inputs.title }}
         DESCRIPTION: ${{ inputs.description }}
+        GITHUB_REPOSITORY: ${{ github.repository }}
       run: |
+        # Escape double quotes '"' => '\"'
+        TITLE=${TITLE//\"/\\\"}
+        DESCRIPTION=${DESCRIPTION//\"/\\\"}
         BASE_BRANCH=$(git rev-parse --abbrev-ref HEAD)
         # Run git commit, push and create pull-request as 'github-actions' user
         git config --local user.name "github-actions"
+        # The 41898282+ email prefixed is the required, matches the ID here
+        # https://api.github.com/users/github-actions%5Bbot%5D
+        # https://github.community/t/github-actions-bot-email-address/17204/6
         git config --local user.email "41898282+github-actions[bot]@users.noreply.github.com"
         git checkout -b "$BRANCH"
         git add .
@@ -48,8 +57,8 @@ runs:
         git push --set-upstream origin "$BRANCH"
         # Create new pull-request via GitHub API
         # https://docs.github.com/en/rest/reference/pulls#create-a-pull-request
-        curl -s \
-        -X POST https://api.github.com/repos/${{ github.repository }}/pulls \
+        RESP_CODE=$(curl -w %{http_code} -s -o /dev/null \
+        -X POST https://api.github.com/repos/$GITHUB_REPOSITORY/pulls \
         -H "Accept: application/vnd.github.v3+json" \
         -H "Authorization: token ${{ github.token }}" \
         -d @- << EOF
@@ -60,4 +69,10 @@ runs:
           "base": "$BASE_BRANCH"
         }
         EOF
-        echo "New pull-request created"
+        )
+        if [[ $RESP_CODE == "201" ]]; then
+          echo "New pull-request created"
+        else
+          echo "Fail to create pull-request - HTTP response code was $RESP_CODE"
+          exit 1
+        fi
